import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { Providers } from '@/providers';
import { cn } from '@/lib/utils';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Search Flights",
  description: "Generated by Muhammad Imam Rozali",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(geistSans.variable, geistMono.variable, 'antialiased')}
        suppressHydrationWarning
        style={{ fontFamily: 'var(--font-geist-sans), system-ui, sans-serif' }}
      >

        <Providers>
          <div className="h-screen w-full overflow-hidden bg-gray-50 dark:bg-gray-900 fixed inset-0">

          {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
